Fixes error when a table doesn't have an header.
The below traceback was returned, due to an empty header element being passed to
`panflute.stringify`.  The idea (according to the code comment above the line in
question -- line 98) is to set this option to True or False depending on whether
there is a header or not.  Thus we just short cirquit this and return False if
the `elem.header` value is None.

----------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/venv2/bin/panflute", line 11, in <module>
    sys.exit(main())
  File "/tmp/venv2/local/lib/python2.7/site-packages/panflute/autofilter.py", line 49, in main
    doc = autorun_filters(filters, doc, extra_path, verbose)
  File "/tmp/venv2/local/lib/python2.7/site-packages/panflute/autofilter.py", line 95, in autorun_filters
    doc = _['main'](doc)
  File "<string>", line 134, in main
  File "/tmp/venv2/local/lib/python2.7/site-packages/panflute/io.py", line 265, in run_filter
    return run_filters([action], *args, **kwargs)
  File "/tmp/venv2/local/lib/python2.7/site-packages/panflute/io.py", line 246, in run_filters
    doc = doc.walk(action, doc)
  File "/tmp/venv2/local/lib/python2.7/site-packages/panflute/base.py", line 274, in walk
    ans = list(chain.from_iterable(ans))
  File "/tmp/venv2/local/lib/python2.7/site-packages/panflute/base.py", line 272, in <genexpr>
    ans = ((item,) if type(item) != list else item for item in ans)
  File "/tmp/venv2/local/lib/python2.7/site-packages/panflute/base.py", line 269, in <genexpr>
    ans = (item.walk(action, doc) for item in obj)
  File "/tmp/venv2/local/lib/python2.7/site-packages/panflute/base.py", line 285, in walk
    altered = action(self, doc)
  File "<string>", line 98, in table2csv
  File "/tmp/venv2/local/lib/python2.7/site-packages/panflute/tools.py", line 212, in stringify
    element.walk(f)
AttributeError: 'NoneType' object has no attribute 'walk'
pandoc: Error running filter panflute
Filter returned error status 1